# R2D6- A markovian approach to write better haikus

Although the haikus so far have matched the 5-7-5 pattern I was looking for, I still think something is missing.  I am going to use Markovify for text generation to see if I can improve this a bit.  I tried n-grams *trigrams and tetragrams* but the process was really slow.  Here is a new angle

### Used the package "Markovify" to generate short sentences

In [1]:
with open ("alice29.txt", 'r') as f:
    text = f.read()

In [2]:
import markovify
text_model = markovify.NewlineText(text, state_size = 3)

In [3]:
sentences = []
for i in range(10):
    sentences.append(text_model.make_sentence())

In [32]:
this= text_model.make_sentence()

In [4]:
sentences

['like the three gardeners, oblong and flat, with their hands and feet, to make the arches.',
 'itself, and was in the pool a',
 'The King turned pale, and shut his eyes.--`Tell her about the reason and all',
 None,
 'first, but, after watching it a minute or two the Caterpillar took the hookah out of its',
 'This question the Dodo could not answer without a great deal too far off to trouble myself',
 'to the baby, and not to her, so she took courage, and went on saying to herself, in a dreamy sort of',
 'last she spread out her hand, and Alice guessed who it was, even before',
 'each side to guard him; and near the King was the White Rabbit, who said in a deep voice, `What',
 'get hold of it; then Alice, thinking it was very provoking to find that the hedgehog had unrolled']

In [38]:
new = text_model.make_sentence()
print(new)
check = syllable_count(new, lang='en-US')
print(check)

about the same height as herself; and when she had got its neck nicely straightened
18

In [55]:

def syllable_count(text, lang='en_US'):
    dic = Pyphen(lang=lang)
    count = 0
    for word in text.split(' '):
        word_hyphenated = dic.inserted(word)
        count += max(1, word_hyphenated.count("-") + 1)
    return count

In [56]:
haikus = []
def makehaikus(n):
    for i in range(n):
        new = text_model.make_sentence()
        check = syllable_count(new, lang='en-US')
        if check == 17:
            haikus.append(new)
    return haikus

In [51]:
haikus = []
def makehaikus(n):
    for i in range (n):
        a = text_model.make_sentence()
        if syllable_count(a) == 17:
            haikus.append(a)
        else:
            print(a)

In [49]:
def makehaikus(n):
    haikus = []
    nhaikus = 0
    if n == nhaikus:
        return haikus
    else:
        for i in range(n):
            a = text_model.make_sentence()
            if syllable_count(a) == 17:
                haikus.append(a)
                nhaikus = nhaikus+1
            else:
                print(a)

In [57]:
makehaikus(10)

AttributeError: 'NoneType' object has no attribute 'split'

In [47]:
haikus

['so grave that she did not like to be a LITTLE larger, sir, if you']

In [34]:
print(this)

`But everything's curious today. I think I could, if I only

### Here I add the syllables to check if the text is haiku

In [40]:
df2 = pd.concat([A2, df], axis = 1)

In [41]:
c = ["word", "syl"]
df2.columns = c
df2

              word  syl
0                [    0
1            Alice    0
2                '    0
3                s    1
4       Adventures    0
5               in    1
6       Wonderland    0
7               by    1
8            Lewis    0
9          Carroll    0
10            1865    0
11               ]    0
12         CHAPTER    0
13               I    0
14               .    0
15            Down    0
16             the    1
17          Rabbit    0
18               -    0
19            Hole    0
20           Alice    0
21             was    1
22       beginning    3
23              to    1
24             get    1
25            very    2
26           tired    2
27              of    1
28         sitting    2
29              by    1
...            ...  ...
34080         feel    1
34081         with    1
34082          all    1
34083        their    1
34084       simple    2
34085      sorrows    2
34086            ,    0
34087          and    1
34088         find    1
34089            a    1
34090     pleasure    2
34091           in    1
34092          all    1
34093        their    1
34094       simple    2
34095         joys    1
34096            ,    0
34097  remembering    3
34098          her    1
34099          own    1
34100        child    1
34101            -    0
34102         life    1
34103            ,    0
34104          and    1
34105          the    1
34106        happy    2
34107       summer    2
34108         days    1
34109            .    0

[34110 rows x 2 columns]

In [42]:
df3 = df2.drop_duplicates(keep=False)
df3

                word  syl
8              Lewis    0
9            Carroll    0
10              1865    0
11                 ]    0
19              Hole    0
63     conversations    4
118            daisy    2
120            chain    1
132          daisies    2
140             pink    1
205         wondered    2
223         actually    3
224             TOOK    0
226            WATCH    0
227              OUT    0
229              ITS    0
230        WAISTCOAT    0
232           POCKET    0
252          flashed    1
267        waistcoat    0
281          burning    2
289            field    1
294      fortunately    4
302              pop    1
345           tunnel    2
367         stopping    2
380           Either    0
396           plenty    2
470             maps    1
473             hung    1
...              ...  ...
33828        choking    2
33863       believed    2
33885        reality    4
33892       rustling    2
33900       rippling    2
33906          reeds    1
33914       tinkling    2
33915          sheep    1
33917          bells    1
33925          cries    1
33931       shepherd    2
33952         noises    2
33963        clamour    0
33966           busy    2
33967           farm    1
33969           yard    1
33973         lowing    2
33976         cattle    2
33993         Lastly    0
33996       pictured    2
34029          riper    0
34030          years    1
34035         loving    2
34039      childhood    2
34045         gather    2
34054          THEIR    0
34085        sorrows    2
34095           joys    1
34097    remembering    3
34106          happy    2

[1360 rows x 2 columns]

In [43]:
df4 = df3[(df3["syl"] != 0) & (df3["word"] != "s")& (df3["word"] != "m")& (df3["word"] != "t")]
df4

                 word  syl
63      conversations    4
118             daisy    2
120             chain    1
132           daisies    2
140              pink    1
205          wondered    2
223          actually    3
252           flashed    1
281           burning    2
289             field    1
294       fortunately    4
302               pop    1
345            tunnel    2
367          stopping    2
396            plenty    2
470              maps    1
473              hung    1
475              pegs    1
493          labelled    2
502    disappointment    4
505             empty    2
512              drop    1
518           killing    2
563             brave    1
643            centre    2
682        schoolroom    2
713          practice    2
720               yes    1
801          downward    2
848           country    2
...               ...  ...
33751          rattle    2
33762          shared    1
33767            meal    1
33803         crashed    1
33828         choking    2
33863        believed    2
33885         reality    4
33892        rustling    2
33900        rippling    2
33906           reeds    1
33914        tinkling    2
33915           sheep    1
33917           bells    1
33925           cries    1
33931        shepherd    2
33952          noises    2
33966            busy    2
33967            farm    1
33969            yard    1
33973          lowing    2
33976          cattle    2
33996        pictured    2
34030           years    1
34035          loving    2
34039       childhood    2
34045          gather    2
34085         sorrows    2
34095            joys    1
34097     remembering    3
34106           happy    2

[993 rows x 2 columns]

In [44]:
df4.reset_index(inplace = True)

df4

     index            word  syl
0       63   conversations    4
1      118           daisy    2
2      120           chain    1
3      132         daisies    2
4      140            pink    1
5      205        wondered    2
6      223        actually    3
7      252         flashed    1
8      281         burning    2
9      289           field    1
10     294     fortunately    4
11     302             pop    1
12     345          tunnel    2
13     367        stopping    2
14     396          plenty    2
15     470            maps    1
16     473            hung    1
17     475            pegs    1
18     493        labelled    2
19     502  disappointment    4
20     505           empty    2
21     512            drop    1
22     518         killing    2
23     563           brave    1
24     643          centre    2
25     682      schoolroom    2
26     713        practice    2
27     720             yes    1
28     801        downward    2
29     848         country    2
..     ...             ...  ...
963  33751          rattle    2
964  33762          shared    1
965  33767            meal    1
966  33803         crashed    1
967  33828         choking    2
968  33863        believed    2
969  33885         reality    4
970  33892        rustling    2
971  33900        rippling    2
972  33906           reeds    1
973  33914        tinkling    2
974  33915           sheep    1
975  33917           bells    1
976  33925           cries    1
977  33931        shepherd    2
978  33952          noises    2
979  33966            busy    2
980  33967            farm    1
981  33969            yard    1
982  33973          lowing    2
983  33976          cattle    2
984  33996        pictured    2
985  34030           years    1
986  34035          loving    2
987  34039       childhood    2
988  34045          gather    2
989  34085         sorrows    2
990  34095            joys    1
991  34097     remembering    3
992  34106           happy    2

[993 rows x 3 columns]

In [45]:
cols = ['word', 'syl']
df5 = df4[cols]
df5

               word  syl
0     conversations    4
1             daisy    2
2             chain    1
3           daisies    2
4              pink    1
5          wondered    2
6          actually    3
7           flashed    1
8           burning    2
9             field    1
10      fortunately    4
11              pop    1
12           tunnel    2
13         stopping    2
14           plenty    2
15             maps    1
16             hung    1
17             pegs    1
18         labelled    2
19   disappointment    4
20            empty    2
21             drop    1
22          killing    2
23            brave    1
24           centre    2
25       schoolroom    2
26         practice    2
27              yes    1
28         downward    2
29          country    2
..              ...  ...
963          rattle    2
964          shared    1
965            meal    1
966         crashed    1
967         choking    2
968        believed    2
969         reality    4
970        rustling    2
971        rippling    2
972           reeds    1
973        tinkling    2
974           sheep    1
975           bells    1
976           cries    1
977        shepherd    2
978          noises    2
979            busy    2
980            farm    1
981            yard    1
982          lowing    2
983          cattle    2
984        pictured    2
985           years    1
986          loving    2
987       childhood    2
988          gather    2
989         sorrows    2
990            joys    1
991     remembering    3
992           happy    2

[993 rows x 2 columns]

In [81]:
s = pd.Series(text_model.make_sentence())
print(s)

0    `We had the best of educations--in fact, we we...
dtype: object

In [67]:
def checksyl(df5, n, sentences):
    #starting with no syllables and no text
    L1 = ""
    nsyl = 0
    
    for word in sentences:
        if word in df5.word:
            nextT = df5.index
            syl = df5.syl[nextT]
            nsyl = nsyl + syl
            next_word = word
            if nsyl == n: #if the right number of syllables is reached
                next_word = text # add new word to the line
                L1 += (str(next_word,)+" ")
                return L1 #exit program, return the line
            elif nsyl < n: #if it is too few syllables
                next_word = text #add the new word to the line
                L1 += (str(next_word,)+" ")
            elif nsyl > n: # if too many syllables
                nsyl = nsyl- syl # subtract number of syllables of new word from total, don't add to line

In [69]:
s = checksyl(df5, 17, sentences)
print(s)

None

In [77]:
syl5lines = []
def syl5line(n):
    for i in range (1 , 2*n):
        line = line1(df5, 5, highfreq)
        if line is not "None":
            syl5lines.append(line)
    return syl5lines
syl5line(10)

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

## Let's attack this from a Markovian perspective

In [2]:
import markovify

In [77]:
import numpy as np
df = pd.Series(syl5lines)
df = df.replace(to_replace='None', value=np.nan).dropna()
df

1                  vulgar added gone
2            partner trials none ill
3               way oh wept produced
4               depends justice kick
5                   attended reduced
6                   chuckled officer
7        sign and thatched left feel
8           sob charges strange want
9              there a grant immense
10             fig tidy moved fright
14             own pack cunning else
15              head lying reeds sat
16             splash unfolded burnt
17              various begged hands
18                use mustard injure
22             top gazing turns fact
24                 whisper bitter as
26            swallow when tones wig
27           complained the mournful
28                character ill bite
29                    why ever apple
31     clubs of fetch dressed fright
32            besides pressing grave
33             bear flying yer creep
34                     being company
35         fountains shrimp while of
36                cunning later half
40               yet sneeze many ate
41                 caterpillar roast
42                   idea kneel that
                    ...
140              letters handwriting
141                   curtain busily
142            look their argue they
146             declared liked giddy
148             book losing as asked
149            emphasis bend twelfth
151                brightened lazily
152             quite noticed stingy
154                     accidentally
156          own branch sounded rise
160              moon verdict follow
164          scream way very thought
167             would signifies with
169            no one follow sneezed
170       liked learnt subjects belt
173              kick tougher was of
174                 disagree besides
175             as learned trees act
177                field unfortunate
179               directed meanwhile
180        top turned her wept speak
181               pleaded alas first
184             some sink glaring we
187                      idiotic use
188             sweet places believe
189            see dark found winter
190       mixed had wrote whiles out
191     he worse hearth bleeds hands
193             sheep cunning finish
198            time further pan else
Length: 112, dtype: object

In [78]:
syl7lines = []
def syl7line(n):
    for i in range (1, n):
        line = line1(df5, 7, s3)
        syl7lines.append(line)
    return syl7lines
syl7line(100)

['stand seated dried know besides ',
 None,
 'disagree chimneys set off ',
 None,
 'mustard presented was great ',
 None,
 None,
 None,
 None,
 None,
 'angrily decided fetch ',
 'shan character to darkness ',
 None,
 'any had closed daughter meant ',
 'but hold lit that run lock laughed ',
 'contemptuously ma give means ',
 None,
 None,
 None,
 'variations kept scream fright ',
 None,
 'look swim put nose mean like dried ',
 None,
 'startled head kills you patience ',
 'pace read of returned pan ran ',
 'cheerfully justice land pretty ',
 'tones expressing any turned ',
 None,
 None,
 'laid somebody handwriting ',
 'juror simple us down ',
 'suppressed but bright ever clasped ',
 'supple contemptuously guests ',
 'enjoy slippery weeks they no ',
 'engaged sing lines flashed own king ',
 'doth sounds calling made guilt throne ',
 'a thought proud come thinking yer ',
 'nibbled grin inquired be ',
 'seated grew opening drunk ',
 'eyelids snout through pepper piece ',
 None,
 None,
 None,
 'smile crawled as affair handsome ',
 'returned blades audibly fig ',
 None,
 None,
 None,
 'purpose honest feel hundred ',
 None,
 None,
 None,
 'land triumphantly squeezed beast ',
 'ten retire way sticks pink ',
 'past after maps but verdict ',
 None,
 'mixed processions vegetable ',
 None,
 'puffed same shade between languid ',
 None,
 'to chin joys anger slippery ',
 None,
 'fairy waste first bitter learnt ',
 'dreaming or subject doze fright ',
 'thank a heart dozing quick him ',
 None,
 None,
 None,
 None,
 'usurpation filled dear son ',
 None,
 'positively eels sugar ',
 'deny shall gay verses fix ',
 None,
 None,
 'hopeless late overhead spot ',
 None,
 'book guard prove commotion brave ',
 'resource words run pencils time ',
 None,
 'lovely cool plainly boon head ',
 None,
 'them cried absurd ears please sweet ',
 'tie would cut officer one ',
 'mice my irons managed faint ',
 'chain leaves pretty adoption ',
 'draw tried up caterpillar ',
 None,
 'decided mind uncivil ',
 'fit tray always feathers mixed ',
 None,
 'punching learn reasonable hands ',
 None,
 'usurpation of word flung ',
 'lamps speed ten lasted at knife ',
 'glaring beating highest fact ',
 'sent there afraid out exact ',
 'heels flying twice with mouse wine ',
 'to carried washing solid ']

In [79]:
df2 = pd.Series(syl7lines)
df2 = df2.replace(to_replace='None', value=np.nan).dropna()
len(df)

112

In [80]:
def haiku(n, df, df2):
    haikus = []
    haikuText = ""
    for i in range (1, n):
        C1 = random.choice(df.index)
        L1 = df[C1]
        C2 = random.choice(df2.index)
        L2 = df2[C2]
        C3 = random.choice(df.index)
        L3 = df[C3]
        haikuText = str(L1)+" "+ str(L2)+" " + str(L3)+" "
        haikus.append(haikuText)
    return haikus

In [81]:
H = haiku(100, df, df2)
H

['caterpillar roast  mixed processions vegetable  various begged hands  ',
 'yet sneeze many ate  engaged sing lines flashed own king  declared liked giddy  ',
 'being company  draw tried up caterpillar  no cleared having been  ',
 'vulgar added gone  lamps speed ten lasted at knife  yet sneeze many ate  ',
 'that set listened rubbed  angrily decided fetch  own branch sounded rise  ',
 'love signed o cherry  seated grew opening drunk  pounds they circle you  ',
 'afraid dream yawning  suppressed but bright ever clasped  rattling shaking  ',
 'use mustard injure  doth sounds calling made guilt throne  character ill bite  ',
 'complained the mournful  mustard presented was great  and run expression  ',
 'hush recovered bells  usurpation of word flung  modern oh dates proud  ',
 'depends justice kick  enjoy slippery weeks they no  quite noticed stingy  ',
 'whisper bitter as  positively eels sugar  leaning finds traps head  ',
 'character complained  land triumphantly squeezed beast  ear neat snorting some  ',
 'attended reduced  seated grew opening drunk  pleaded alas first  ',
 'frowning search did soft  book guard prove commotion brave  sneezed bells shiny cur  ',
 'cunning later half  startled head kills you patience  song forgotten doze  ',
 'she received knife roast  doth sounds calling made guilt throne  field unfortunate  ',
 'reasons drowned over  fairy waste first bitter learnt  various begged hands  ',
 'hush recovered bells  decided mind uncivil  some sink glaring we  ',
 'nibbled bear dodged use  angrily decided fetch  he worse hearth bleeds hands  ',
 'louder paused globe live  punching learn reasonable hands  afraid dream yawning  ',
 'and run expression  lovely cool plainly boon head  afraid dream yawning  ',
 'whisper dripping lark  any had closed daughter meant  some sink glaring we  ',
 'idea kneel that  decided mind uncivil  minutes being twice  ',
 'emphasis bend twelfth  doth sounds calling made guilt throne  half nothing twenty  ',
 'but seem sleepy fast  deny shall gay verses fix  past accounting use  ',
 'see dark found winter  any had closed daughter meant  lately counting found  ',
 'curtain busily  punching learn reasonable hands  field unfortunate  ',
 'declared liked giddy  draw tried up caterpillar  fountains shrimp while of  ',
 'else teapot alone  sent there afraid out exact  modern oh dates proud  ',
 'treated saucer wept  angrily decided fetch  uncomfortably wife  ',
 'moon verdict follow  look swim put nose mean like dried  scream way very thought  ',
 'sweet places believe  disagree chimneys set off  uncomfortably wife  ',
 'reasons drowned over  stand seated dried know besides  free another flew  ',
 'ear neat snorting some  angrily decided fetch  twelve tunnel dismay  ',
 'but seem sleepy fast  stand seated dried know besides  cunning later half  ',
 'attended reduced  look swim put nose mean like dried  field unfortunate  ',
 'kick tougher was of  shan character to darkness  pegs whistle sharks squeezed  ',
 'duck after condemn  shan character to darkness  pegs whistle sharks squeezed  ',
 'pleaded alas first  mixed processions vegetable  sob charges strange want  ',
 'scream eagerly goose  deny shall gay verses fix  modern oh dates proud  ',
 'besides pressing grave  puffed same shade between languid  quite noticed stingy  ',
 'that set listened rubbed  cheerfully justice land pretty  timid steam denied  ',
 'as learned trees act  contemptuously ma give means  louder paused globe live  ',
 'kick tougher was of  usurpation of word flung  clubs of fetch dressed fright  ',
 'complained the mournful  thank a heart dozing quick him  use mustard injure  ',
 'crust balls pressing laugh  doth sounds calling made guilt throne  declared liked giddy  ',
 'swallow when tones wig  tie would cut officer one  head lying reeds sat  ',
 'no one follow sneezed  to carried washing solid  using pence see then  ',
 'using pence see then  usurpation filled dear son  whisper dripping lark  ',
 'various begged hands  past after maps but verdict  book losing as asked  ',
 'complained the mournful  thank a heart dozing quick him  various begged hands  ',
 'modern oh dates proud  positively eels sugar  modern oh dates proud  ',
 'see dark found winter  them cried absurd ears please sweet  sob charges strange want  ',
 'being company  deny shall gay verses fix  minutes being twice  ',
 'use mustard injure  nibbled grin inquired be  fig tidy moved fright  ',
 'head lying reeds sat  fairy waste first bitter learnt  declared liked giddy  ',
 'ear neat snorting some  look swim put nose mean like dried  nibbled bear dodged use  ',
 'mixed had wrote whiles out  angrily decided fetch  ear neat snorting some  ',
 'idiotic use  eyelids snout through pepper piece  but seem sleepy fast  ',
 'whisper bitter as  them cried absurd ears please sweet  would signifies with  ',
 'learnt shared seemed pot bread  heels flying twice with mouse wine  bear flying yer creep  ',
 'mixed had wrote whiles out  angrily decided fetch  pounds they circle you  ',
 'frightened sneeze of shan  usurpation filled dear son  reasons drowned over  ',
 'caterpillar roast  seated grew opening drunk  besides pressing grave  ',
 'mixed had wrote whiles out  look swim put nose mean like dried  liked learnt subjects belt  ',
 'interrupt pulled close  dreaming or subject doze fright  dressed upright respect  ',
 'sheep cunning finish  any had closed daughter meant  pegs whistle sharks squeezed  ',
 'word hiss pan modern  mixed processions vegetable  would signifies with  ',
 'idiotic use  thank a heart dozing quick him  interrupt pulled close  ',
 'partner trials none ill  lovely cool plainly boon head  twelve tunnel dismay  ',
 'fountains shrimp while of  doth sounds calling made guilt throne  reasons drowned over  ',
 'treated saucer wept  angrily decided fetch  mixed had wrote whiles out  ',
 'there a grant immense  returned blades audibly fig  he worse hearth bleeds hands  ',
 'interrupt pulled close  chain leaves pretty adoption  chuckled officer  ',
 'idea kneel that  decided mind uncivil  word hiss pan modern  ',
 'hush recovered bells  book guard prove commotion brave  attended reduced  ',
 'field unfortunate  positively eels sugar  fig tidy moved fright  ',
 'disagree besides  startled head kills you patience  louder paused globe live  ',
 'quite noticed stingy  usurpation filled dear son  why ever apple  ',
 'own branch sounded rise  book guard prove commotion brave  way oh wept produced  ',
 'emphasis bend twelfth  cheerfully justice land pretty  half nothing twenty  ',
 'kick tougher was of  enjoy slippery weeks they no  else teapot alone  ',
 'using pence see then  but hold lit that run lock laughed  caterpillar roast  ',
 'past accounting use  mustard presented was great  own pack cunning else  ',
 'various begged hands  shan character to darkness  clubs of fetch dressed fright  ',
 'he worse hearth bleeds hands  deny shall gay verses fix  disobey speak there  ',
 'he worse hearth bleeds hands  mustard presented was great  modern oh dates proud  ',
 'vulgar added gone  purpose honest feel hundred  besides pressing grave  ',
 'own branch sounded rise  seated grew opening drunk  half nothing twenty  ',
 'subdued down unless  a thought proud come thinking yer  no cleared having been  ',
 'besides pressing grave  fit tray always feathers mixed  sob charges strange want  ',
 'field unfortunate  smile crawled as affair handsome  swallow when tones wig  ',
 'idea kneel that  mice my irons managed faint  kick tougher was of  ',
 'timid steam denied  stand seated dried know besides  depends justice kick  ',
 'use mustard injure  chain leaves pretty adoption  sneezed bells shiny cur  ',
 'mixed had wrote whiles out  angrily decided fetch  past accounting use  ',
 'quite noticed stingy  fit tray always feathers mixed  that set listened rubbed  ',
 'top gazing turns fact  to carried washing solid  she received knife roast  ']

In [82]:
def writeHaikus(haikuList):
    with open("genHaikusBigrams.txt", "w") as fp:
        count = 0
        for item in haikuList:
            fp.write("%s\n" % item)
            fp.write("\n")
            count += 1
        print ("There are", count, "lines in your file.")

In [83]:
writeHaikus(H)

There are 99 lines in your file.